version: "3.9"

services:
  db:
    container_name: m4_capstone_returning
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
